export const US_STATES = [
  'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
  'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
  'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
  'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
  'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
  'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
  'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
  'Wisconsin', 'Wyoming',
]

export const CITIES_BY_STATE: Record<string, string[]> = {
  Alabama: [
    'Alabaster', 'Anniston', 'Athens', 'Auburn', 'Bessemer', 'Birmingham', 'Calera',
    'Cullman', 'Decatur', 'Dothan', 'Enterprise', 'Florence', 'Gadsden', 'Homewood',
    'Hoover', 'Huntsville', 'Madison', 'Mobile', 'Montgomery', 'Muscle Shoals',
    'Northport', 'Opelika', 'Oxford', 'Phenix City', 'Prattville', 'Saraland',
    'Tuscaloosa', 'Vestavia Hills',
  ],
  Alaska: [
    'Anchorage', 'Badger', 'College', 'Fairbanks', 'Juneau', 'Ketchikan', 'Kodiak',
    'Sitka', 'Wasilla',
  ],
  Arizona: [
    'Ahwatukee', 'Apache Junction', 'Avondale', 'Buckeye', 'Bullhead City', 'Casa Grande',
    'Catalina Foothills', 'Chandler', 'Flagstaff', 'Gilbert', 'Glendale', 'Goodyear',
    'Lake Havasu City', 'Marana', 'Maricopa', 'Mesa', 'Oro Valley', 'Peoria', 'Phoenix',
    'Prescott', 'Prescott Valley', 'Queen Creek', 'Sahuarita', 'San Tan Valley',
    'Scottsdale', 'Sierra Vista', 'Surprise', 'Tempe', 'Tucson', 'Yuma',
  ],
  Arkansas: [
    'Bentonville', 'Bryant', 'Conway', 'Fayetteville', 'Fort Smith', 'Hot Springs',
    'Jonesboro', 'Little Rock', 'North Little Rock', 'Pine Bluff', 'Rogers', 'Russellville',
    'Searcy', 'Sherwood', 'Springdale', 'Texarkana', 'Van Buren', 'West Memphis',
  ],
  California: [
    'Alameda', 'Alhambra', 'Anaheim', 'Antioch', 'Apple Valley', 'Bakersfield',
    'Baldwin Park', 'Berkeley', 'Buena Park', 'Burbank', 'Carson', 'Chico', 'Chino',
    'Chino Hills', 'Chula Vista', 'Citrus Heights', 'Clovis', 'Compton', 'Concord',
    'Corona', 'Costa Mesa', 'Daly City', 'Davis', 'Downey', 'El Cajon', 'El Monte',
    'Elk Grove', 'Escondido', 'Fairfield', 'Fontana', 'Fremont', 'Fresno', 'Fullerton',
    'Garden Grove', 'Glendale', 'Hawthorne', 'Hayward', 'Hemet', 'Hesperia',
    'Huntington Beach', 'Inglewood', 'Irvine', 'Lancaster', 'Livermore', 'Long Beach',
    'Los Angeles', 'Menifee', 'Mission Viejo', 'Modesto', 'Moreno Valley', 'Murrieta',
    'Norwalk', 'Oakland', 'Oceanside', 'Ontario', 'Orange', 'Oxnard', 'Palmdale',
    'Pasadena', 'Pomona', 'Rancho Cucamonga', 'Redding', 'Rialto', 'Richmond',
    'Riverside', 'Roseville', 'Sacramento', 'Salinas', 'San Bernardino', 'San Buenaventura',
    'San Diego', 'San Francisco', 'San Jose', 'San Mateo', 'Santa Ana', 'Santa Clara',
    'Santa Clarita', 'Santa Rosa', 'Simi Valley', 'Stockton', 'Sunnyvale', 'Temecula',
    'Thousand Oaks', 'Torrance', 'Turlock', 'Vacaville', 'Vallejo', 'Victorville',
    'Visalia', 'West Covina',
  ],
  Colorado: [
    'Arvada', 'Aurora', 'Boulder', 'Broomfield', 'Castle Rock', 'Centennial',
    'Colorado Springs', 'Commerce City', 'Denver', 'Fort Collins', 'Grand Junction',
    'Greeley', 'Highlands Ranch', 'Lakewood', 'Littleton', 'Longmont', 'Loveland',
    'Parker', 'Pueblo', 'Thornton', 'Westminster',
  ],
  Connecticut: [
    'Bridgeport', 'Bristol', 'Danbury', 'Greenwich', 'Hartford', 'Manchester',
    'Meriden', 'Middletown', 'Milford', 'New Britain', 'New Haven', 'Norwalk',
    'Shelton', 'Stamford', 'Stratford', 'Waterbury', 'West Hartford', 'West Haven',
  ],
  Delaware: [
    'Bear', 'Dover', 'Middletown', 'Milford', 'Newark', 'Smyrna', 'Wilmington',
  ],
  Florida: [
    'Altamonte Springs', 'Boca Raton', 'Boynton Beach', 'Bradenton', 'Brandon',
    'Cape Coral', 'Clearwater', 'Coconut Creek', 'Coral Gables', 'Coral Springs',
    'Daytona Beach', 'Davie', 'Deerfield Beach', 'Deltona', 'Dunedin', 'Fort Lauderdale',
    'Fort Myers', 'Gainesville', 'Hialeah', 'Hollywood', 'Homestead', 'Jacksonville',
    'Jupiter', 'Kissimmee', 'Lakeland', 'Largo', 'Lauderhill', 'Margate', 'Melbourne',
    'Miami', 'Miami Gardens', 'Miramar', 'Naples', 'North Miami', 'Oakland Park',
    'Ocala', 'Orlando', 'Palm Bay', 'Palm Beach Gardens', 'Pembroke Pines', 'Pensacola',
    'Plantation', 'Pompano Beach', 'Port Orange', 'Port St. Lucie', 'Sarasota',
    'Spring Hill', 'St. Cloud', 'St. Petersburg', 'Sunrise', 'Tallahassee', 'Tampa',
    'Weston', 'West Palm Beach',
  ],
  Georgia: [
    'Albany', 'Alpharetta', 'Athens', 'Atlanta', 'Augusta', 'Canton', 'Columbus',
    'Dalton', 'Douglasville', 'Dunwoody', 'East Point', 'Gainesville', 'Johns Creek',
    'Kennesaw', 'Lawrenceville', 'Macon', 'Marietta', 'Milton', 'Newnan', 'Peachtree City',
    'Roswell', 'Sandy Springs', 'Savannah', 'Smyrna', 'Valdosta', 'Warner Robins',
    'Woodstock',
  ],
  Hawaii: [
    'Hilo', 'Honolulu', 'Kailua', 'Kaneohe', 'Mililani', 'Pearl City', 'Waipahu',
  ],
  Idaho: [
    'Boise', 'Caldwell', "Coeur d'Alene", 'Idaho Falls', 'Lewiston', 'Meridian',
    'Moscow', 'Nampa', 'Pocatello', 'Post Falls', 'Rexburg', 'Twin Falls',
  ],
  Illinois: [
    'Algonquin', 'Aurora', 'Bloomington', 'Bolingbrook', 'Buffalo Grove', 'Champaign',
    'Chicago', 'Crystal Lake', 'Decatur', 'Des Plaines', 'Elgin', 'Elk Grove Village',
    'Elmhurst', 'Evanston', 'Hoffman Estates', 'Joliet', 'Lombard', 'Moline',
    'Mount Prospect', 'Naperville', 'Normal', 'Oak Lawn', 'Oak Park', 'Orland Park',
    'Palatine', 'Peoria', 'Rockford', 'Schaumburg', 'Skokie', 'Springfield',
    'St. Charles', 'Tinley Park', 'Waukegan', 'Wheaton',
  ],
  Indiana: [
    'Anderson', 'Bloomington', 'Carmel', 'Columbus', 'Elkhart', 'Evansville', 'Fishers',
    'Fort Wayne', 'Gary', 'Greenwood', 'Hammond', 'Indianapolis', 'Kokomo', 'Lafayette',
    'Lawrence', 'Mishawaka', 'Muncie', 'Noblesville', 'South Bend', 'Terre Haute',
    'Westfield',
  ],
  Iowa: [
    'Ames', 'Ankeny', 'Cedar Falls', 'Cedar Rapids', 'Council Bluffs', 'Davenport',
    'Des Moines', 'Dubuque', 'Iowa City', 'Marion', 'Sioux City', 'Waterloo',
    'West Des Moines',
  ],
  Kansas: [
    'Kansas City', 'Lawrence', 'Lenexa', 'Manhattan', 'Olathe', 'Overland Park',
    'Salina', 'Shawnee', 'Topeka', 'Wichita',
  ],
  Kentucky: [
    'Bowling Green', 'Covington', 'Elizabethtown', 'Florence', 'Georgetown',
    'Henderson', 'Hopkinsville', 'Lexington', 'Louisville', 'Nicholasville',
    'Owensboro', 'Paducah', 'Richmond',
  ],
  Louisiana: [
    'Alexandria', 'Baton Rouge', 'Bossier City', 'Houma', 'Kenner', 'Lafayette',
    'Lake Charles', 'Metairie', 'Monroe', 'New Orleans', 'Shreveport',
  ],
  Maine: [
    'Auburn', 'Augusta', 'Bangor', 'Biddeford', 'Lewiston', 'Portland', 'Saco',
    'South Portland',
  ],
  Maryland: [
    'Annapolis', 'Baltimore', 'Bowie', 'College Park', 'Columbia', 'Frederick',
    'Gaithersburg', 'Germantown', 'Hagerstown', 'Laurel', 'Rockville', 'Salisbury',
    'Silver Spring', 'Waldorf',
  ],
  Massachusetts: [
    'Boston', 'Brockton', 'Cambridge', 'Chicopee', 'Fall River', 'Framingham',
    'Haverhill', 'Holyoke', 'Lawrence', 'Lowell', 'Lynn', 'Malden', 'Medford',
    'New Bedford', 'Newton', 'Peabody', 'Pittsfield', 'Quincy', 'Revere', 'Salem',
    'Somerville', 'Springfield', 'Taunton', 'Waltham', 'Weymouth', 'Worcester',
  ],
  Michigan: [
    'Ann Arbor', 'Battle Creek', 'Bay City', 'Clinton Township', 'Dearborn',
    'Dearborn Heights', 'Detroit', 'Farmington Hills', 'Flint', 'Grand Rapids',
    'Kalamazoo', 'Lansing', 'Livonia', 'Macomb', 'Midland', 'Muskegon',
    'Pontiac', 'Rochester Hills', 'Roseville', 'Royal Oak', 'Saginaw',
    'Shelby Township', 'Southfield', 'Sterling Heights', 'Taylor', 'Troy',
    'Warren', 'Westland', 'Wyoming',
  ],
  Minnesota: [
    'Apple Valley', 'Blaine', 'Bloomington', 'Brooklyn Center', 'Brooklyn Park',
    'Burnsville', 'Coon Rapids', 'Duluth', 'Eagan', 'Eden Prairie', 'Edina',
    'Lakeville', 'Maple Grove', 'Minneapolis', 'Minnetonka', 'Moorhead',
    'Plymouth', 'Rochester', 'Roseville', 'Saint Paul', 'St. Cloud',
    'Woodbury',
  ],
  Mississippi: [
    'Biloxi', 'Gulfport', 'Hattiesburg', 'Jackson', 'Meridian', 'Olive Branch',
    'Oxford', 'Pearl', 'Southaven', 'Tupelo',
  ],
  Missouri: [
    'Blue Springs', 'Columbia', 'Florissant', 'Independence', 'Jefferson City',
    'Joplin', "Lee's Summit", 'Liberty', "O'Fallon", 'Kansas City', 'Raytown',
    'Springfield', 'St. Charles', 'St. Joseph', 'St. Louis', 'St. Peters',
  ],
  Montana: [
    'Billings', 'Bozeman', 'Butte', 'Great Falls', 'Helena', 'Kalispell', 'Missoula',
  ],
  Nebraska: [
    'Bellevue', 'Fremont', 'Grand Island', 'Hastings', 'Kearney', 'Lincoln',
    'Norfolk', 'Omaha', 'Papillion',
  ],
  Nevada: [
    'Carson City', 'Elko', 'Enterprise', 'Henderson', 'Las Vegas', 'North Las Vegas',
    'Paradise', 'Reno', 'Sparks', 'Spring Valley', 'Sunrise Manor', 'Whitney',
  ],
  'New Hampshire': [
    'Concord', 'Derry', 'Dover', 'Keene', 'Manchester', 'Merrimack', 'Nashua',
    'Portsmouth', 'Rochester', 'Salem',
  ],
  'New Jersey': [
    'Bayonne', 'Brick', 'Camden', 'Cherry Hill', 'Clifton', 'Edison', 'Elizabeth',
    'Hamilton', 'Jersey City', 'Lakewood', 'Newark', 'New Brunswick', 'Passaic',
    'Paterson', 'Toms River', 'Trenton', 'Union City', 'Vineland', 'Woodbridge',
  ],
  'New Mexico': [
    'Albuquerque', 'Clovis', 'Farmington', 'Hobbs', 'Las Cruces', 'Rio Rancho',
    'Roswell', 'Santa Fe', 'Sunland Park',
  ],
  'New York': [
    'Albany', 'Binghamton', 'Bronx', 'Brooklyn', 'Buffalo', 'Cheektowaga',
    'Freeport', 'Hempstead', 'Manhattan', 'Mount Vernon', 'New Rochelle',
    'New York City', 'Niagara Falls', 'Queens', 'Rochester', 'Rome',
    'Schenectady', 'Staten Island', 'Syracuse', 'Troy', 'Utica',
    'White Plains', 'Yonkers',
  ],
  'North Carolina': [
    'Apex', 'Asheville', 'Burlington', 'Cary', 'Chapel Hill', 'Charlotte',
    'Concord', 'Durham', 'Fayetteville', 'Gastonia', 'Greensboro', 'Greenville',
    'High Point', 'Hickory', 'Holly Springs', 'Huntersville', 'Indian Trail',
    'Jacksonville', 'Kannapolis', 'Matthews', 'Monroe', 'Mooresville', 'Raleigh',
    'Rocky Mount', 'Wilmington', 'Wilson', 'Winston-Salem',
  ],
  'North Dakota': [
    'Bismarck', 'Fargo', 'Grand Forks', 'Minot', 'West Fargo', 'Williston',
  ],
  Ohio: [
    'Akron', 'Canton', 'Cincinnati', 'Cleveland', 'Cleveland Heights', 'Columbus',
    'Cuyahoga Falls', 'Dayton', 'Dublin', 'Elyria', 'Euclid', 'Fairfield',
    'Hamilton', 'Kettering', 'Lakewood', 'Lorain', 'Mansfield', 'Mentor',
    'Middletown', 'Newark', 'Parma', 'Springfield', 'Toledo', 'Warren',
    'Westerville', 'Youngstown',
  ],
  Oklahoma: [
    'Bartlesville', 'Broken Arrow', 'Edmond', 'Enid', 'Lawton', 'Midwest City',
    'Moore', 'Muskogee', 'Norman', 'Oklahoma City', 'Owasso', 'Shawnee',
    'Stillwater', 'Tulsa',
  ],
  Oregon: [
    'Beaverton', 'Bend', 'Corvallis', 'Eugene', 'Gresham', 'Hillsboro', 'Medford',
    'Portland', 'Salem', 'Springfield', 'Tigard',
  ],
  Pennsylvania: [
    'Allentown', 'Altoona', 'Bethlehem', 'Erie', 'Harrisburg', 'Lancaster',
    'Levittown', 'Philadelphia', 'Pittsburgh', 'Reading', 'Scranton',
    'Upper Darby', 'Wilkes-Barre', 'York',
  ],
  'Rhode Island': [
    'Cranston', 'East Providence', 'Newport', 'Pawtucket', 'Providence',
    'Warwick', 'Woonsocket',
  ],
  'South Carolina': [
    'Bluffton', 'Charleston', 'Columbia', 'Florence', 'Goose Creek', 'Greenville',
    'Hilton Head Island', 'Mauldin', 'Mount Pleasant', 'Myrtle Beach',
    'North Charleston', 'Rock Hill', 'Spartanburg', 'Summerville', 'Sumter',
  ],
  'South Dakota': [
    'Aberdeen', 'Brookings', 'Mitchell', 'Rapid City', 'Sioux Falls', 'Watertown',
  ],
  Tennessee: [
    'Bartlett', 'Brentwood', 'Chattanooga', 'Clarksville', 'Collierville',
    'Franklin', 'Hendersonville', 'Jackson', 'Johnson City', 'Kingsport',
    'Knoxville', 'Memphis', 'Morristown', 'Murfreesboro', 'Nashville',
    'Smyrna', 'Spring Hill',
  ],
  Texas: [
    // Major cities
    'Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso',
    'Arlington', 'Corpus Christi', 'Laredo', 'Lubbock', 'Garland', 'Irving',
    'Amarillo', 'Brownsville', 'McAllen', 'Waco', 'Midland', 'Odessa',
    'Killeen', 'Beaumont', 'Tyler', 'Abilene', 'Edinburg', 'Wichita Falls',
    'San Angelo',
    // Dallas / DFW suburbs
    'Plano', 'McKinney', 'Frisco', 'Denton', 'Grand Prairie', 'Mesquite',
    'Richardson', 'Carrollton', 'Allen', 'Lewisville', 'Flower Mound',
    'Cedar Hill', 'Euless', 'Bedford', 'Grapevine', 'Hurst', 'Mansfield',
    'Rowlett', 'Wylie', 'Coppell', 'Rockwall', 'Southlake', 'Keller',
    'North Richland Hills', 'Desoto', 'Duncanville', 'Burleson',
    'Little Elm', 'Forney', 'Fate', 'Prosper', 'Celina', 'Waxahachie',
    'Saginaw', 'Crowley',
    // Houston area suburbs
    'Sugar Land', 'Pearland', 'League City', 'Pasadena', 'The Woodlands',
    'Conroe', 'Katy', 'Spring', 'Cypress', 'Humble', 'Baytown',
    'Missouri City', 'Friendswood', 'Rosenberg', 'Richmond', 'Kingwood',
    'Tomball', 'Atascocita', 'Stafford', 'Deer Park', 'La Porte',
    'Galveston', 'Texas City', 'Webster', 'Manvel', 'Pearland',
    'Sienna', 'Alvin', 'Angleton', 'Clute', 'Lake Jackson',
    // San Antonio area
    'New Braunfels', 'Seguin', 'Schertz', 'Cibolo', 'Universal City',
    'San Marcos', 'Kyle', 'Buda', 'Boerne', 'Converse', 'Live Oak',
    'Leon Valley', 'Selma',
    // Austin area
    'Round Rock', 'Cedar Park', 'Georgetown', 'Pflugerville', 'Leander',
    'Hutto', 'Buda', 'Kyle', 'Lakeway', 'Cedar Hill',
    // Other notable cities
    'Longview', 'Nacogdoches', 'Lufkin', 'Texarkana', 'Marshall',
    'Harlingen', 'Mission', 'Pharr', 'Weslaco', 'Temple', 'Belton',
    'Stephenville', 'Weatherford', 'Cleburne', 'Corsicana',
  ],
  Utah: [
    'American Fork', 'Cedar City', 'Clearfield', 'Draper', 'Herriman',
    'Kaysville', 'Layton', 'Lehi', 'Logan', 'Murray', 'Ogden', 'Orem',
    'Pleasant Grove', 'Provo', 'Riverton', 'Roy', 'Salt Lake City',
    'Sandy', 'South Jordan', 'Spanish Fork', 'Springville', 'St. George',
    'Taylorsville', 'Tooele', 'West Jordan', 'West Valley City',
  ],
  Vermont: [
    'Burlington', 'Colchester', 'Essex', 'Montpelier', 'Rutland',
    'South Burlington', 'St. Albans',
  ],
  Virginia: [
    'Alexandria', 'Arlington', 'Blacksburg', 'Charlottesville', 'Chesapeake',
    'Danville', 'Hampton', 'Harrisonburg', 'Leesburg', 'Lynchburg', 'Manassas',
    'Newport News', 'Norfolk', 'Portsmouth', 'Reston', 'Richmond', 'Roanoke',
    'Suffolk', 'Virginia Beach',
  ],
  Washington: [
    'Auburn', 'Bellevue', 'Bellingham', 'Bremerton', 'Burien', 'Edmonds',
    'Everett', 'Federal Way', 'Kennewick', 'Kent', 'Kirkland', 'Lacey',
    'Marysville', 'Olympia', 'Pasco', 'Redmond', 'Renton', 'Richland',
    'Sammamish', 'Seattle', 'Shoreline', 'Spokane', 'Spokane Valley',
    'Tacoma', 'Vancouver', 'Yakima',
  ],
  'West Virginia': [
    'Charleston', 'Clarksburg', 'Huntington', 'Martinsburg', 'Morgantown',
    'Parkersburg', 'Wheeling',
  ],
  Wisconsin: [
    'Appleton', 'Beloit', 'Eau Claire', 'Green Bay', 'Janesville', 'Kenosha',
    'La Crosse', 'Madison', 'Milwaukee', 'Mount Pleasant', 'Neenah',
    'Oshkosh', 'Racine', 'Sheboygan', 'Waukesha', 'Wausau', 'West Allis',
  ],
  Wyoming: [
    'Casper', 'Cheyenne', 'Gillette', 'Laramie', 'Rock Springs', 'Sheridan',
  ],
}

export const COUNTRIES = [
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'New Zealand',
  'Ireland',
  'Germany',
  'France',
  'Netherlands',
  'Sweden',
  'Norway',
  'Denmark',
  'Switzerland',
  'Austria',
  'Belgium',
  'Italy',
  'Spain',
  'Portugal',
  'Poland',
  'Czech Republic',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Ghana',
  'Ethiopia',
  'Brazil',
  'Mexico',
  'Colombia',
  'Argentina',
  'Chile',
  'Peru',
  'Jamaica',
  'Trinidad and Tobago',
  'Barbados',
  'India',
  'Philippines',
  'South Korea',
  'Singapore',
  'Japan',
  'Other',
]

export const EDUCATION_OPTIONS = [
  'High School',
  'Some College',
  "Associate's Degree",
  "Bachelor's Degree",
  "Master's Degree",
  'Doctorate',
  'Trade/Vocational',
  'Other',
]
